import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@samplemail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'user@samplemail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Desktop PC type 01',
      slug: 'destop-pc-type-01',
      category: 'computer',
      image: '/images/computer1.jpg',
      price: 70,
      brand: 'ewis',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Desktop PC type 01',
    },
    {
      name: 'Desktop PC type 02',
      slug: 'destop-pc-type-02',
      category: 'computer',
      image: '/images/computer2.jpg',
      price: 70,
      brand: 'hp',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Desktop PC type 02',
    },
    {
      name: 'Desktop PC type 03',
      slug: 'destop-pc-type-03',
      category: 'computer',
      image: '/images/computer3.jpg',
      price: 70,
      brand: 'dell',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Desktop PC type 03',
    },
    {
      name: 'Laptop Type 01',
      slug: 'laptop-type-01',
      category: 'laptop',
      image: '/images/laptop1.jpg',
      price: 70,
      brand: 'asus',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Laptop type 01',
    },
    {
      name: 'Laptop Type 02',
      slug: 'laptop-type-02',
      category: 'laptop',
      image: '/images/laptop2.jpg',
      price: 70,
      brand: 'hp',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Laptop type 01',
    },
    {
      name: 'Laptop Type 03',
      slug: 'laptop-type-03',
      category: 'acer',
      image: '/images/laptop3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Laptop type 01',
    },
    {
      name: 'Laptop Type 04',
      slug: 'laptop-type-04',
      category: 'msi',
      image: '/images/laptop4.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Laptop type 01',
    },
  ],
};
export default data;
