const data = {
  products: [
    {
      name: 'Desktop PC type 01',
      category: 'computer',
      image: '/images/computer1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Desktop PC type 01',
    },
    {
      name: 'Desktop PC type 02',
      category: 'computer',
      image: '/images/computer2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Desktop PC type 02',
    },
    {
      name: 'Desktop PC type 03',
      category: 'computer',
      image: '/images/computer3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Desktop PC type 03',
    },
    {
      name: 'Laptop Type 01',
      category: 'laptop',
      image: '/images/laptop1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Laptop type 01',
    },
    {
      name: 'Laptop Type 02',
      category: 'laptop',
      image: '/images/laptop2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Laptop type 01',
    },
    {
      name: 'Laptop Type 03',
      category: 'laptop',
      image: '/images/laptop3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Laptop type 01',
    },
    {
      name: 'Laptop Type 04',
      category: 'laptop',
      image: '/images/laptop4.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Description on Laptop type 01',
    },
  ],
};
export default data;
